### ISSUE TITLE
[Pre-release] Game crashes on launch. Windwos 10 x64 1607 LTSB

### ISSUE THREAD

**Issue by shale1337** [MaksVe/LNCF#3]
Happens for first time launching the game.

**Comment by MaksVe** [comment]
Changing compatibility modes seems to help, though I'm not sure how to fix it.

**Comment by MaksVe** [comment]
The issue was resolved. Due to uninitialized variable bool ScreenManager::QuitGameFromMenu was almost always true (thanks, reddit: https://www.reddit.com/r/gamedev/comments/8qmpc1/ive_built_a_small_game_with_c_and_sdl2_but_i_cant/).
